spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://127.0.0.1:3306/blog?serverTimezone=UTC
    username: root
  thymeleaf:
    cache: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      # 上传文件总的最大值
      max-request-size: 10MB
mybatis:
  #mapper-locations: classpath:com/yjdxs/blog/mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.yjdxs.blog.entity  # 注意：对应实体类的路径
  configuration:
    #org.apache.ibatis.logging.stdout.StdOutImpl 控制台打印sql语句方便调试sql语句执行错误
    #org.apache.ibatis.logging.log4j2.Log4j2Impl:这个不在控制台打印查询结果,但是在log4j中打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #mapUnderscoreToCamelCase: true # 开启驼峰命名转换法

# 指定log4j2作为日志记录
logging:
    level:
    #这个指定你的dao层，也就是mapper文件的所在包
      com.yjdxs.blog.mapper: DEBUG
    
